### PR TITLE
Release version 1.0.0

### PR DESCRIPTION
**Pull request by aedart**
Hi Sebastian

It would be really great if you could release this package as version 1.0.x, so that we can start using it without having to fetch your dev-master.

### CODE REVIEW

**Comment by aedart** [comment]
NB: It seems that I am not allowed to "tag" a version via pull requests, meaning that you will have to do this.

**Comment by binsoul** [comment]
I think it's too early for a 1.0 release because there are a lot of tests missing. But I tagged the current state as version 0.1.0.

I would like to drop support for PHP 5.6 in this package and require PHP 7.0+. Do you need PHP 5.6 compatibility or would this be ok for you?

**Comment by aedart** [comment]
Hi again

A version 0.1 will do just fine. The intended purpose is to be able to use your https://github.com/binsoul/net-mqtt-client-react package, in which I saw that you had a dev dependency. I would appreciate it a lot, if you also could tag your MQTT react based client.

NB: We  (Vestergaard Company) are using it for a custom RPC framework over MQTT.

In regards to PHP version, sadly we are yet not able to switch to PHP 7.x. We have a lot of packages and dependencies that are still not ready for such a migration. Nevertheless, sometime in the future we will of course adapt.

It would mean a lot for us, if you could continue a little while with v5.6. Perhaps you could release a version 1 supporting 5.6 and then plan support for PHP 7 for a version 2? (Thinking in terms of http://semver.org/). Should we come across anything, then we will try to fix it, create a pull request and then you can decide if it can be used or otherwise.

Just out of curiosity, how far are you from completing you MQTT React client, when not considering your wish for PHP 7?

Anyways, thanks a lot for your efforts - we do enjoy working with your code :)

**Comment by binsoul** [comment]
Thats why I was asking. I wanted to know if I can switch to PHP 7 in version 1.0 or if I have to keep PHP 5.6 compatibility for 1.0 and drop it in version 2.0. This should be no problem.

The React client definitely needs to be splitted into multiple classes which shouldn't change it's public API. It also needs some more features like subscribing to multiple topics in one call. But it runs here for almost 6 months now, being restarted only 2 or 3 times, so it feels quite stable to me.

**Comment by aedart** [comment]
We too feel that your client behaves very stable and are really looking forward to a release upon it :)
Whenever you can manage such, will be fine for us. Our project is still in an early stage, so it will take us some time before version locking is that relevant. But, as mentioned, we still need to develop it for v.5.6, due to integration with other components.

Once again, thanks for your efforts and we look forward to see your packages in action :)

**Pull request closed without merging**
